### ISSUE TITLE
Add support for .NET 6 / Maui

### ISSUE THREAD

**Issue by tranb3r** [dotMorten/MSTestX#15]
There is a PR for adding support for .NET 6 / Maui.
It seems it's still work in progress.
Do you plan on releasing it soon ?

**Comment by dotMorten** [comment]
Probably not until early next year when the need for this will come up and maui stabilizes a bit more

**Comment by dotMorten** [comment]
...feel free to use the branch. The feedback could help

**Comment by DrSchiwago74** [comment]
I saw a lot of progress in .NET MAUI. Is there a way to setup a project using .NET MAUI?
I would like to reference projects based on .net6.0. Xamarin.Forms projects have only target Frameworks based on .NET Standard.

**Comment by dotMorten** [comment]
Use the v2 previews with Maui on nuget.

**Comment by andy-waxman** [comment]
FYI The "Run Test" button is not visible on Windows. It is present and responds to click events as expected.  Using 2.0.0-preview4
![Screenshot 2023-01-10 082313](https://user-images.githubusercontent.com/6384715/211606505-d94462f6-1233-4daf-973d-92ad6b6e901b.png)

**Comment by dotMorten** [comment]
The Windows build is only there for some light easy testing - on Windows you'd use regular MSTest in test explorer.

**Comment by dotMorten** [comment]
this was completed a while back
