### ISSUE TITLE
Readme Usage point 4 and 5 incorrect.

### ISSUE THREAD

**Issue by stevefriesen** [dotMorten/MSTestX#5]
The Readme Usage section points 4 and 5 says to change code to LoadApplication(new TestAppRunner.App()). From what I can tell there is no TestAppRunner.App constructor. There is a MSTestX.RunnerApp() constructor which is of type Xamarin.Forms.Application.

**Comment by dotMorten** [comment]
Thanks for pointing this out! Fixed now.

Sorry I apparently wasn't watching my own repo, so didn't notice you logged this until now :)
